name: ${plugin.name}
version: ${plugin.version}
main: ${plugin.main}
description: ${plugin.description}
author: ${plguin.author}
website: ${plugin.website}

commands:
  tamatool:
    description: ${plugin.description}
    usage: /tamatool <subcommand>
    aliases: [tt, tama]

permissions:
  tamatool.version:
    default: op