name: ${plugin.name}
version: ${plugin.version}
main: ${plugin.main}
description: ${plugin.description}
author: ${plguin.author}
website: ${plugin.website}

commands:
  tamatool:
    description: ${plugin.description}
    usage: /tamatool <command> [OPTION]...
    aliases: [tt, tama]

permissions:
  tamatool.help:
    default: op
  tamatool.version:
    default: op
  tamatool.blockinfo:
    default: op